
services:
  postgres:
    image: postgres:latest
    container_name: personal_webpage
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-password}
      POSTGRES_DB: ${PG_DATABASE:-personal_webpage}
    ports:
        - "${PG_PORT:-5432}:5432"
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data

  