export const experienceSeed = [
    {
      color: "#66ff99",
      startDate: new Date("2024-06-01"),
      endDate: new Date("2024-11-01"),
      title: "KOKTEM.DEV",
      position: "Lead Software Engineer",
      place: "Almaty, Kazakhstan",
      baseDescription: "Startup specializing in outsourcing services",
      skills: [
        "Redis",
        "Docker",
        "Bash",
        "Linux",
        "Node.js",
        "FSD",
        "Vue3.js",
        "React.js",
        "Three.js",
        "WebGL",
        "PostgreSQL",
      ],
      cards: [
        {
          text: "`Led` a development team at Koktem.dev to `deliver tailored web solutions, improving business outcomes` for multiple clients. `Guided` the development team through `structured workflows, established coding standards`, and `implemented best practices` for `scalable architecture`",
          variant: 3,
          imageUrls: ["https://cdn.anoirs-personal-page.com/workflow.webp"],
        },
      ],
    },
    {
      color: "#00ff99",
      startDate: new Date("2023-11-01"),
      endDate: new Date("2024-06-01"),
      title: "DEMETRA SYSTEMS",
      position: "Team Lead Full-stack Software Engineer",
      place: "Almaty, Kazakhstan",
      baseDescription:
        "DEMETRA SYSTEMS automates pricing adjustments for marketplace sellers",
      skills: [
        "Redis",
        "Docker",
        "Network",
        "Netplan",
        "Node.js",
        "Nest.js",
        "Clean Architecture",
        "Vue3.js",
        "PostgreSQL",
      ],
      cards: [
        {
          text: "Oversaw the `scaling of databases` and `Redis` using master-slave configurations, and `multiplied instances` of code blocks using `PM2` for enhanced performance and reliability.",
          linkSrc: "https://demetra.systems/",
          linkLabel: "DEMETRA SYSTEMS",
          variant: 2,
          imageUrls: [
            "https://cdn.anoirs-personal-page.com/demetra-desktop.webp",
            "https://cdn.anoirs-personal-page.com/demetra-mobile.webp",
          ],
        },
        {
          text: "`Implemented` and `streamlined` the `development lifecycle` from ClickUp ticket creation, Git branch management, and pull request descriptions for QA, through to `dockerized CI/CD` pipeline setup and `load balancing`. This involved managing ticket workflows, automating documentation for completed tickets, and `ensured seamless integration`.",
          linkSrc: "https://demetra.systems/",
          linkLabel: "DEMETRA SYSTEMS",
          variant: 1,
          imageUrls: [
            "https://cdn.anoirs-personal-page.com/demetra-pipeline.webp",
          ],
        },
      ],
    },
    {
      color: "#FF824C",
      startDate: new Date("2023-03-01"),
      endDate: new Date("2023-10-01"),
      title: "Careerist",
      position: "Full-stack Developer",
      place: "Remote (Based Miami, FL)",
      baseDescription:
        "`Careerist`is a `Learning Management System ( LMS ) platform` designed to facilitate online learning and professional development. Features such as courses, certifications, and tools for managing and tracking learning progress, aimed at both individual learners and organizations seeking to enhance employee skills and knowledge.",
      skills: [
        "Bash",
        "Linux",
        "Node.js",
        "Molecular.js",
        "React.js",
        "Sockets",
        "MySQL",
      ],
      cards: [
        {
          text: "`Developed` new pages on the website using `React.js` and `Moleculer.js` (backend), maintained and enhanced functionality, implemented a client chat, and optimized the search system, `improving` its `performance by 4 times`.",
          linkSrc: "https://www.careerist.com/",
          linkLabel: "Careerist.com",
          variant: 3,
          imageUrls: ["https://cdn.anoirs-personal-page.com/careerist.webp"],
        },
      ],
    },
    {
      color: "#003d99",
      startDate: new Date("2021-07-01"),
      endDate: new Date("2022-12-01"),
      title: "Powr.io",
      position: "Full-stack Developer",
      place: "Remote (Based San Francisco, CA)",
      baseDescription:
        "`POWR.io` offers customizable plugins for websites, including forms, galleries, social media feeds, and timers. It enhances user engagement and site functionality across platforms like WordPress and Shopify, making it accessible for users seeking to improve their online presence.",
      skills: [
        "Ruby on Rails",
        "Bash",
        "Linux",
        "Node.js",
        "Next.js",
        "React.js",
      ],
      cards: [
        {
          text: "Worked with a team of developers to `add features`, `fix bugs`, `internal integrations`, and make upgrades to existing applications. \n\nHelped the company increase customer traffic by writing `customizable 1 billion landing pages` with 12 languages to `improve Web Crawling and SEO.`",
          linkSrc: "https://www.powr.io/form-builder-website-app",
          linkLabel: "POWR.io Form builder",
          variant: 3,
          imageUrls: ["https://cdn.anoirs-personal-page.com/powr-logo.webp"],
        },
        {
          text: "`Developed an integration system` to `automate interaction` between developers and team members, providing `chat notifications`, `ticket movements`, and `automatic documentation` of completed tickets and `CI/CD` providing the company with a full development lifecycle.",
          linkSrc: "https://powr.io/",
          linkLabel: "POWR.io",
          variant: 1,
          imageUrls: ["https://cdn.anoirs-personal-page.com/powrio.webp"],
        },
      ],
    },
    {
      color: "#80d4ff",
      startDate: new Date("2020-01-01"),
      endDate: new Date("2021-07-01"),
      title: "NCRM GROUP",
      position: "Front-End Developer and Project Manager",
      place: "Almaty, Kazakhstan",
      baseDescription: "NCRM - Simple CRM for Systematic Sales",
      skills: ["Angular 10", "Jasmine.js", "Vue.js", "Vite", "Docker"],
      cards: [
        {
          text: "`Developed` the `front-end infrastructure` and `prototype` for a CRM project. The `MVP` was used by a company with over `2000+ employees`.",
          linkSrc: "https://ncrm.kz/",
          linkLabel: "NCRM.KZ",
          variant: 1,
          imageUrls: ["https://cdn.anoirs-personal-page.com/ncrm.webp"],
        },
        {
          text: "Significantly increased `code maintainability` and support by writing the project documentation. \n\n Integrated `web chat` inside CRM with popular messengers, such as `Whatsapp` and `Telegram`. Utilized free and premium APIs of those messengers for companies to communicate with their customers through our chat interface.",
          linkSrc: "asdf",
          linkLabel: "asdfasdf",
          variant: 2,
          imageUrls: [
            "https://cdn.anoirs-personal-page.com/ncrm-desktop.webp",
            "https://cdn.anoirs-personal-page.com/ncrm-mobile.webp",
          ],
        },
      ],
    },
  ];
  